### ISSUE TITLE
Old release in Atom package manager

### ISSUE THREAD

**Issue by conFusl** [mackoj/language-gherkin-i18n#10]
Hi Jeffrey,

I tried to reinstall the package in Atom to check the fixes we made in November, but when I try to install it I get still version 1.2.0 and not 1.2.1 as your latest release. Do you have to modify something in the Atom package manager, does it not automatically grab the latest release? 
BR

**Comment by nixel2007** [comment]
Looks like package wasn't published (or maybe was unpublished).

**Comment by mackoj** [comment]
This will be fix today

**Comment by mackoj** [comment]
Is the last update fix this issue ?

**Comment by nixel2007** [comment]
Fixed.

**Comment by conFusl** [comment]
Does the automatic language detection work with version 1.3.0 when you try some files? I have the same problem as before.

**Comment by nixel2007** [comment]
no, it doesn't work for me.

**Comment by mackoj** [comment]
Atom path CRLF support so the fix is not needed anymore.
So I disabled it and replublish

**Comment by conFusl** [comment]
thx
