### ISSUE TITLE
Keywords sorting in regexp

### ISSUE THREAD

**Issue by nixel2007** [mackoj/language-gherkin-i18n#11]
When you have 2 keywords in regexp 
And first keyword is a start-part of the second keyword
Then second keyword is highlighted incorectly.

As you can see [here](https://github.com/mackoj/language-gherkin-i18n/blob/develop/grammars/gherkin_ru.cson#L96) "То" is a start-part of the word "Тогда". And when you write "Тогда" in a file only "To" is highlighted.

![default](https://cloud.githubusercontent.com/assets/1132840/12489835/6b4d3f0a-c083-11e5-8a64-dbe66ac2aca4.PNG)

The solution is to sort keywords some way, so "Тогда" will be before "То" in regexp

**Comment by mackoj** [comment]
The best way to fix it is to fix it at the source. https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json

**Comment by mackoj** [comment]
Fix in version v1.3.2

**Comment by nixel2007** [comment]
Fixed, thanks!
