### ISSUE TITLE
Color highlighting after keywords

### ISSUE THREAD

**Issue by conFusl** [mackoj/language-gherkin-i18n#13]
When addressing a parameter next to a gherkin keyword, the parameter will not be highlighted, only with an extra space character: 
![image](https://cloud.githubusercontent.com/assets/7404242/12752386/9ed77f00-c9c2-11e5-9b5c-53e967dc7e0d.png)

When inserting an extra space character, the parameter will be highlighted:
![image](https://cloud.githubusercontent.com/assets/7404242/12752417/c583a368-c9c2-11e5-80eb-bb78e042d230.png)

**Comment by mackoj** [comment]
Thanks for this issue. This is a bug and I will look into it when I can.

**Comment by conFusl** [comment]
Already found the problem, will try to fix the other issue with the examples table as well and commit all changes. Would it be OK for you when I push the changes to the repo and you regenerate all files?

**Comment by mackoj** [comment]
Yes for sure
