### ISSUE TITLE
Error messages in console

### ISSUE THREAD

**Issue by nixel2007** [mackoj/language-gherkin-i18n#15]
In console you can find a bunch of errors like: `Error setting item in object: Validation failed at editor.increaseIndentPattern, ["Scenario: .*"] must be null`

`increaseIndentPattern` must be a string with reg exp. In this package `increaseIndentPattern` is a array of strings.

Check:
this package - https://github.com/mackoj/language-gherkin-i18n/blob/develop/settings/language-gherkin_en.cson#L19
language-1c-bsl - https://github.com/xDrivenDevelopment/atom-language-1c-bsl/blob/master/settings/language-1c-bsl.cson#L7

**Comment by nixel2007** [comment]
I think, changing the template here https://github.com/mackoj/language-gherkin-i18n/blob/develop/generators/template/gherkin_settings_template.cson#L15 and regenerating settings should be enough for fix this issue.

**Comment by mackoj** [comment]
Hi, I'm sink these days I gonna take a look into it this weekend.
