### ISSUE TITLE
Not working -- spanish -- Atom.

### ISSUE THREAD

**Issue by Xosmond** [mackoj/language-gherkin-i18n#17]
Any reason why this wouldn't work? It's only working on english mode, even when i put "# language: es" on the first line.
![captura de pantalla 2016-04-29 a las 1 56 51 p m](https://cloud.githubusercontent.com/assets/11930063/14926580/7809ab7a-0e12-11e6-9920-d54a5b988cea.png)

**Comment by mackoj** [comment]
Strange,

Look at the bottom right coner of your screen and try to set it manually by clicking on Gherkin(-en). A pop-up will appear and type gherkin-es to force spanish.

Please consider send me your feature file for testing.

Cheers,

**Comment by mackoj** [comment]
Maybe try to put an empty line after #language: es

**Comment by Xosmond** [comment]
Setting manually to Gherking-es works. Thanks.
