### ISSUE TITLE
Atom doesn't respond any more just after installing the package

### ISSUE THREAD

**Issue by pablodgcatulo** [mackoj/language-gherkin-i18n#18]
I'm sory, I don't know how to post information relevant to this bug, but that's the effect. Just after installing the package, atom doesn't respond any more.

If kill the process and restart atom, i can't start atom again. The window opens, but it' doesn't start.  The only way to resolve this is using amp remove lenguage-gherking-i18n, but I want to use this package (it's great!). 

I'm using fedora 25 (x64), 
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

If you could point me up what to look for, i would be glad to help. I just use atom, but don't know how it works and how i can fix it.

thanks!

**Comment by mackoj** [comment]
Hi @pablodgcatulo,

I'm sorry to ear this. I tried it this morning on my mac and it to worked. 
I don't have a linux computer to test it. So you will have to debug it by yourself and do a Pull Request.

Go to this page http://flight-manual.atom.io/hacking-atom/sections/debugging/ :
- Find Crash Logs
- Diagnose Startup Performance
- Diagnose Runtime Performance
- Profiling Startup Performance

And post here if you find some useful information, I will try to help.

Cheers,

**Comment by pablodgcatulo** [comment]
Found it! The problem was releated with this package https://github.com/reergymerej/todo. I didn't test it with atom last release (1.13.0) but, all was resolved after I remove that package. 

Thanks for the tips :)
