### ISSUE TITLE
Words like 'Eu', 'Ela' are highlighted in Descriptions 

### ISSUE THREAD

**Issue by gsmiro** [mackoj/language-gherkin-i18n#3]
In the below example: 
```gherkin
Funcionalidade: Teste
  Como um usuário
  Eu me logo no sistema
```
The 'E' in 'Eu' in the description's second line gets highlighted.
Version is 1.2.0 in Atom 0.184.0 on Ubuntu.

**Comment by mackoj** [comment]
I need to have more info in order to help you like the LangID you defined in your file.

Cheers,

**Comment by mackoj** [comment]
Is the last update fix this issue ? If it ok please close this issue.

**Comment by mackoj** [comment]
Related to issue #11 fix
