### ISSUE TITLE
Wrong language detected on CRLF line endings

### ISSUE THREAD

**Issue by MDM23** [mackoj/language-gherkin-i18n#4]
Hi there,

I just noticed that the language detection doesn't work on my windows machine. It uses "Gherkin-af" for all files with CRLF endings. When I convert a file to LF, everything is working well. Looking forward a fix as your gherkin plugin is the only one that works great with other languages :)

Thanks and regards,
Peter

**Comment by mackoj** [comment]
Thanks

**Comment by mackoj** [comment]
This could help https://github.com/atom/line-ending-selector I will try to find the time to fix it.

**Comment by conFusl** [comment]
I think I found the solution: 
Change line 23 in language-gherkin-i18n/generators/generateGlobalConfig.php from 

`$firstLineMatchLine = "'firstLineMatch' : '^# language: __LANG__$'";` 
to 
`$firstLineMatchLine = "'firstLineMatch' : '^# language: __LANG__$(\r)?\n'";`

I tested it on my PC and the language detection worked also with CLRF file ending. 

BR,
Ewald

**Comment by mackoj** [comment]
Is the last update fix this issue ? If it ok please close this issue.

**Comment by mackoj** [comment]
Fix by atom since and the last version v1.3.1 handle this modification
