### ISSUE TITLE
Wrong syntax coloring 

### ISSUE THREAD

**Issue by conFusl** [mackoj/language-gherkin-i18n#5]
Hi, 
I've installed the Atom editor and your plugin to syntax color and highlight gherkin-specific keywords, but it seems that it doesn't work as expected. When I install and enable the plugin "language-gherkin"  the .feature file looks like this: 
![image](https://cloud.githubusercontent.com/assets/7404242/11340231/55311eda-91fd-11e5-8524-4d42d5f93698.png)

When I use the plugin "language-gherkin-i18n" and open the same file, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/7404242/11340279/845d00fc-91fd-11e5-9eaf-e295ac019072.png)

Do I have to install other dependencies or adjust some settings to achieve the result you are showing in your examples? 

BR

**Comment by mackoj** [comment]
It's related to this issues https://github.com/mackoj/language-gherkin-i18n/issues/4

**Comment by mackoj** [comment]
Is the last update fix this issue ?

**Comment by mackoj** [comment]
Work on the last version
