### ISSUE TITLE
Space at parameter in scenario outline

### ISSUE THREAD

**Issue by nixel2007** [mackoj/language-gherkin-i18n#7]
Screenshot is the best:

![default](https://cloud.githubusercontent.com/assets/1132840/12413111/7be239ca-be9d-11e5-9bc2-6ec619409f50.PNG)

There are no restrictions to have spaces in parameters' names.
I can change the regexp by myself and make a PR, if you point me to it.

**Comment by mackoj** [comment]
I will be glad if you do so.
