### ISSUE TITLE
Support new gherkin-languages.json in Gherkin repo

### ISSUE THREAD

**Issue by mackoj** [mackoj/language-gherkin-i18n#9]
Change parser and generator in order to support new https://github.com/cucumber/gherkin/blob/master/gherkin-languages.json which is the new format of i18n.json file.

**Comment by nixel2007** [comment]
+1 for support new file!
There are some nice wording improvements for my language.

**Comment by mackoj** [comment]
It has been done it will be release today

**Comment by mackoj** [comment]
Is the last update fix this issue ?

**Comment by nixel2007** [comment]
Looks like fixed
